<?php

/**
 * PhotoCategoryValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoCategoryValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoCategoryValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoCategoryValue');
    }
}