<?php

/**
 * PhotoRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoRating');
    }
}