<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }
    
    public function getRecent($limit = null) {
        $q = $this->createQuery()
                ->select()
                ->orderBy('created_at DESC');
                
        if($limit){
            $q->limit($limit);
        }

        return $q->execute();
    }

}

