<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/20 22:14:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=photka',
  'username' => 'photka',
  'password' => 'photka',
  'name' => 'doctrine',
)),);
