<?php

/**
 * BasePhotoCategoryValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $photo_id
 * @property integer $category_value_id
 * @property Photo $Photo
 * @property CategoryValue $CategoryValue
 * 
 * @method integer            getPhotoId()           Returns the current record's "photo_id" value
 * @method integer            getCategoryValueId()   Returns the current record's "category_value_id" value
 * @method Photo              getPhoto()             Returns the current record's "Photo" value
 * @method CategoryValue      getCategoryValue()     Returns the current record's "CategoryValue" value
 * @method PhotoCategoryValue setPhotoId()           Sets the current record's "photo_id" value
 * @method PhotoCategoryValue setCategoryValueId()   Sets the current record's "category_value_id" value
 * @method PhotoCategoryValue setPhoto()             Sets the current record's "Photo" value
 * @method PhotoCategoryValue setCategoryValue()     Sets the current record's "CategoryValue" value
 * 
 * @package    photka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoCategoryValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_category_value');
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_value_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id'));

        $this->hasOne('CategoryValue', array(
             'local' => 'category_value_id',
             'foreign' => 'id'));
    }
}