<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Photos
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getPhotos() Returns the current record's "Photos" collection
 * @method Category            setName()   Sets the current record's "name" value
 * @method Category            setPhotos() Sets the current record's "Photos" collection
 * 
 * @package    photka
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Photo as Photos', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}