generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Photo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [name, category, description, location, path, is_public]
      filter:  
        display: [name, category_id, description, is_public]
      form:    
        display: [name, category_id, description, location, path, is_public]
      edit:    ~
      new:     ~
