<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/07 20:36:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=photka',
  'username' => 'wpz',
  'password' => 'photka007',
  'name' => 'doctrine',
)),);
