Category:
  columns:
    name: { type: string(255), notnull: true, unique: true }
 
Photo:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    name:         { type: string(255) }
    location:     { type: string(255), notnull: true }
    description:  { type: string(4000), notnull: true }
    token:        { type: string(255), notnull: true, unique: true }
    is_public:    { type: boolean, notnull: true, default: 0 }
    path:        { type: string(255), notnull: true }
  relations:
    Category: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: Photos   } 
 
